# Generated by Django 5.2.17 on 2026-08-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0002_transfer_status_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                (
                    "provider_transfer_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "provider_status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("payload_fingerprint", models.CharField(max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("ignored_terminal", "Ignored terminal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_events",
                        to="transfers.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
